# Generated by Django 3.2.5 on 2021-07-25 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water_usage', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('friends_list', models.ManyToManyField(blank=True, default='users', related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('person_of', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
