# Generated by Django 3.2.5 on 2021-07-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_usage',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
