# Generated by Django 3.2.5 on 2021-07-25 08:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0002_profile_total_usage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='master_list', to='frontend.masterlist')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(blank=True, default='', max_length=150, null=True)),
                ('footprint', models.FloatField(blank=True, default=0, null=True)),
                ('food_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='frontend.foodlist')),
            ],
        ),
    ]
