# Generated by Django 3.2.5 on 2021-07-25 00:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0006_auto_20210724_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends_list',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL),
        ),
    ]
