# Generated by Django 3.2.5 on 2021-07-25 01:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0011_alter_profile_person_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='person_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_id', to=settings.AUTH_USER_MODEL),
        ),
    ]
