# Generated by Django 3.2.5 on 2021-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_alter_profile_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.AddField(
            model_name='profile',
            name='friends_list',
            field=models.ManyToManyField(blank=True, related_name='friends', to='frontend.Profile'),
        ),
    ]
